spring:
  datasource:
    url: jdbc:mysql://localhost:3306/investCalc?useSSL=false
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver

  config:
    import: [moex.yml, jwt.yml]

  jpa:
    hibernate:
      ddl-auto: update  # Стратегия создания и обновления базы данных
    show-sql: false  # Показывать SQL-запросы
    properties:
      hibernate.format_sql: true  # Форматирование SQL-запросов